### ISSUE TITLE
Bug? `--vae-tiling` produces very obvious seams/artifacts near the edge of each "tiles"

### ISSUE THREAD

**Issue by stduhpf** [leejet/stable-diffusion.cpp#353] opened 2024-08-20 15:18 UTC
Case and point:

`.\build\bin\Release\sd.exe -m ..\models\checkpoints\sd3_medium_incl_clips_t5xxlfp16.safetensors --cfg-scale 5 --steps 20 --sampling-method euler  -H 1024 -W 1024 --seed 42 -p "professional   photo of a girl laying down on grass, fine details, 4k resolution" --vae-tiling`
![output](https://github.com/user-attachments/assets/04346558-b660-488c-bcac-3746117d46ac)

I can almost count all the 64 tiles by eye. I don't think that's the expected behavior.

For comparison, here is with normal vae on cpu:
![output](https://github.com/user-attachments/assets/7b0025dd-d42c-4965-8361-662ff98030de)

**Comment by MGTRIDER** [comment] 2024-08-25 04:24
> Case and point:
> 
> `.\build\bin\Release\sd.exe -m ..\models\checkpoints\sd3_medium_incl_clips_t5xxlfp16.safetensors --cfg-scale 5 --steps 20 --sampling-method euler -H 1024 -W 1024 --seed 42 -p "professional photo of a girl laying down on grass, fine details, 4k resolution" --vae-tiling` ![output](https://private-user-images.githubusercontent.com/28208228/359531676-04346558-b660-488c-bcac-3746117d46ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ1NjAxMTYsIm5iZiI6MTcyNDU1OTgxNiwicGF0aCI6Ii8yODIwODIyOC8zNTk1MzE2NzYtMDQzNDY1NTgtYjY2MC00ODhjLWJjYWMtMzc0NjExN2Q0NmFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI1VDA0MjMzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhZThhZjBkODc1OWU3NDY2YTNhMDQxZjA1NDE2MTUyODNmOTIzMTIwNjhkZTEwODM1MDljNjc4MTExYTI0ZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vHcRoG7FUFBA1mhPuFAoXP_vxtzMGrhOH7dGC6Rtcg4)
> 
> I can almost count all the 64 tiles by eye. I don't think that's the expected behavior.
> 
> For comparison, here is with normal vae on cpu: ![output](https://private-user-images.githubusercontent.com/28208228/359537014-7b0025dd-d42c-4965-8361-662ff98030de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ1NjAxMTYsIm5iZiI6MTcyNDU1OTgxNiwicGF0aCI6Ii8yODIwODIyOC8zNTk1MzcwMTQtN2IwMDI1ZGQtZDQyYy00OTY1LTgzNjEtNjYyZmY5ODAzMGRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI1VDA0MjMzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhYWQ2NjRjOWEwM2M5MDg3NDZkY2I4YzljNjI3NmE4ZTVhYzQ4MzY5ZWFjODA2OTAwYjhlYjg1ZjJlYjg2MDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aEDtuNiCW7obFekxN0PrQ-oOFRVcNPXkHHH2VV3qh4Y)

Yes, i can confirm that these seams also happen for me when using tiled vae.

**Comment by Green-Sky** [comment] 2024-08-26 11:26
This has been an issue for a long time now, so I am currently investigating.
Here is a test image, which replaces each tile with a single uniform color (grayscale). The lines are the midway points of the overlap.
![artius_output](https://github.com/user-attachments/assets/b196d873-93b5-460b-af00-a912812b0377)
You can clearly see seams, basically everywhere beside the outermost tiles. So only the outermost with the next seem to be merged (lerped) correctly.

**Comment by Green-Sky** [comment] 2024-08-26 11:42
I am relatively confident that the current interpolation function blends like this:
![image](https://github.com/user-attachments/assets/0d780a18-881d-4266-8e1a-a737fce94492)

so I am trying to make it looks like this:

![image](https://github.com/user-attachments/assets/6f3deef3-f5ee-4e9c-8a8e-16ab3d7bf398)

**Comment by Green-Sky** [comment] 2024-08-26 11:45
![artius_output](https://github.com/user-attachments/assets/411208ed-be13-4a79-addb-03cfa9fa9487)

Hmmm, this still has issues...

**Comment by Green-Sky** [comment] 2024-08-26 12:13
| old merge | new merge |
|------------|-----------------------------------------------------------------------------|
| ![vae_lerp_new](https://github.com/user-attachments/assets/a39febf3-bd8e-4787-8cf7-3248b3554ac0) | ![artius_output](https://github.com/user-attachments/assets/c0b3c48e-999d-42ea-9715-e78963480467) |
| no tiling | lines at mid-overlap |
| ![vae_no_tiling](https://github.com/user-attachments/assets/d2666b33-f6eb-4fc9-9745-4b976c6938b9) | ![vae_debug_corner_smoother](https://github.com/user-attachments/assets/6f0e241f-af85-4728-b51f-74db3133cd3e) |

new merge is using `lerp(a, b, smootherstep(min(x ,y)))`


I think this is good enough for a pr, I will open one soon if I don't have anymore insights into whats wrong or could be better.

**Comment by stduhpf** [comment] 2024-08-26 12:41
> I think this is good enough for a pr, I will open one soon if I don't have anymore insights into whats wrong or could be better.

Please do, maybe i could help figuring it out

**Closed** 2024-08-27 16:21 UTC
